spring:
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: '1KB'
      max-file-size: '10MB'
      max-request-size: '10MB'

  datasource:    
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgres://${DB_HOST}:${DB_PORT}/${DB_NAME}

# Server Error Path
server:
  error:
    path: /error
  port: 8080
